<?php namespace App\Http\Controllers\API;

use League\Fractal\Serializer\DataArraySerializer;

class Serializer extends DataArraySerializer
{
    public function item($resourceKey, array $data)
    {
        $data['type'] = $resourceKey;

        if ($resourceKey == 'event' && isset($data['location']['data']))
            $data['location'] = $data['location']['data'];

        return parent::item($resourceKey, $data); // TODO: Change the autogenerated stub
    }
}
